import React, { useState, useEffect } from 'react';
import axios from 'axios';
import * as Lucide from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
// ප්‍රස්ථාර සඳහා Recharts import කිරීම
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';

function AppointmentPage() {
    const [appointments, setAppointments] = useState([]);
    const [formData, setFormData] = useState({ nic: '', reason: '', date: '', time: '' });
    const [searchQuery, setSearchQuery] = useState('');
    const [error, setError] = useState('');
    
    const user = JSON.parse(localStorage.getItem('user'));
    const isOfficer = user?.role === 'officer';

    useEffect(() => { fetchAppointments(); }, []);

    const fetchAppointments = async () => {
        try {
            const res = await axios.get('https://villageflow-backend.onrender.com/api/appointments/all');
            setAppointments(res.data);
        } catch (err) { console.error("Error fetching data", err); }
    };

    // --- PDF වාර්තාව සෑදීමේ Function එක ---
    const downloadPDF = () => {
        const doc = new jsPDF();
        doc.setFontSize(18);
        doc.setTextColor(128, 0, 0); 
        doc.text("Smart Appointment System - Official Report", 14, 15);
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 22);
        doc.text(`Generated by: ${user?.name || user?.username || 'Officer'}`, 14, 27);

        const tableColumn = ["User Name", "NIC", "Reason", "Date", "Time", "Status"];
        const tableRows = [];

        filteredAppointments.forEach(app => {
            const finalUserName = app.userName || app.name || app.username || "Unknown User";
            const rowData = [
                finalUserName,
                app.nic || "N/A",
                app.reason || "N/A",
                app.date || "N/A",
                app.time || "N/A",
                app.status || "Pending"
            ];
            tableRows.push(rowData);
        });

        autoTable(doc, {
            head: [tableColumn],
            body: tableRows,
            startY: 35,
            theme: 'striped',
            headStyles: { fillColor: [128, 0, 0] },
            styles: { fontSize: 9 }
        });

        doc.save(`Appointments_Report_${new Date().toLocaleDateString()}.pdf`);
    };

    const validateNIC = (nic) => {
        const oldNIC = /^[0-9]{9}[vVxX]$/;
        const newNIC = /^[0-9]{12}$/;
        return oldNIC.test(nic) || newNIC.test(nic);
    };

    const handleBook = async (e) => {
        e.preventDefault();
        setError('');
        if (!validateNIC(formData.nic)) {
            setError('කරුණාකර නිවැරදි NIC අංකයක් ඇතුළත් කරන්න.');
            return;
        }
        try {
            const bookingData = { 
                ...formData, 
                userId: user.id || user._id, 
                userName: user.name || user.fullName || user.username || "User",
                userEmail: user.email // Email එක Backend එකට යවනවා Notification සඳහා
            };
            await axios.post('https://villageflow-backend.onrender.com/api/appointments/book', bookingData);
            alert("ඉල්ලීම සාර්ථකයි!");
            setFormData({ nic: '', reason: '', date: '', time: '' });
            fetchAppointments();
        } catch (err) { alert("වෙන් කිරීම අසාර්ථකයි"); }
    };

    const updateStatus = async (id, newStatus) => {
        try {
            await axios.put(`https://villageflow-backend.onrender.com/api/appointments/status/${id}`, { status: newStatus });
            fetchAppointments();
        } catch (err) { alert("Error updating status"); }
    };

    const deleteAppointment = async (id) => {
        if (window.confirm("මෙම පත්වීම මකා දැමීමට ඔබට සහතිකද?")) {
            try {
                await axios.delete(`https://villageflow-backend.onrender.com/api/appointments/${id}`);
                fetchAppointments();
            } catch (err) { alert("මකා දැමීම අසාර්ථකයි"); }
        }
    };

    const filteredAppointments = appointments
        .filter(app => isOfficer ? true : app.userId === (user?.id || user?._id))
        .filter(app => {
            const name = (app.userName || app.name || app.username || "").toLowerCase();
            const nic = (app.nic || "");
            return name.includes(searchQuery.toLowerCase()) || nic.includes(searchQuery);
        });

    // Chart එක සඳහා දත්ත සකස් කිරීම
    const chartData = [
        { name: 'Pending', count: appointments.filter(a => a.status === 'Pending').length, color: '#f59e0b' },
        { name: 'Approved', count: appointments.filter(a => a.status === 'Approved').length, color: '#22c55e' },
        { name: 'Rejected', count: appointments.filter(a => a.status === 'Rejected').length, color: '#ef4444' },
    ];

    return (
        <div style={styles.container}>
            <div style={styles.headerRow}>
                <h2 style={styles.mainTitle}>
                    <Lucide.CalendarCheck color="#800000" size={28} /> Smart Appointments
                </h2>
                <button onClick={downloadPDF} style={styles.pdfBtn}>
                    <Lucide.FileText size={18} /> Download Report
                </button>
            </div>

            {/* Stats Summary Cards */}
            <div style={styles.statsRow}>
                {chartData.map((stat, index) => (
                    <div key={index} style={{...styles.statCard, borderLeft: `5px solid ${stat.color}`}}>
                        <span style={styles.statLabel}>{stat.name}</span>
                        <h4 style={styles.statValue}>{stat.count}</h4>
                    </div>
                ))}
            </div>

            {/* Chart Section (දත්ත දෘශ්‍යකරණය) */}
            {isOfficer && (
                <div style={styles.chartSection}>
                    <h3 style={{fontSize: '16px', marginBottom: '15px'}}>Appointment Overview</h3>
                    <div style={{ height: 200 }}>
                        <ResponsiveContainer width="100%" height="100%">
                            <BarChart data={chartData}>
                                <XAxis dataKey="name" fontSize={12} />
                                <YAxis fontSize={12} />
                                <Tooltip cursor={{fill: 'transparent'}} />
                                <Bar dataKey="count" radius={[4, 4, 0, 0]}>
                                    {chartData.map((entry, index) => (
                                        <Cell key={`cell-${index}`} fill={entry.color} />
                                    ))}
                                </Bar>
                            </BarChart>
                        </ResponsiveContainer>
                    </div>
                </div>
            )}

            {!isOfficer && (
                <div style={styles.formSection}>
                    <h3>නව පත්වීමක් වෙන් කරවා ගන්න</h3>
                    {error && <p style={styles.errorMsg}>{error}</p>}
                    <form onSubmit={handleBook} style={styles.form}>
                        <input type="text" placeholder="NIC" value={formData.nic} onChange={e => setFormData({...formData, nic: e.target.value})} style={styles.input} required />
                        <input type="text" placeholder="හේතුව" value={formData.reason} onChange={e => setFormData({...formData, reason: e.target.value})} style={styles.input} required />
                        <div style={styles.row}>
                            <input type="date" value={formData.date} onChange={e => setFormData({...formData, date: e.target.value})} style={{...styles.input, flex: 1}} required />
                            <input type="time" value={formData.time} onChange={e => setFormData({...formData, time: e.target.value})} style={{...styles.input, flex: 1}} required />
                        </div>
                        <button type="submit" style={styles.bookBtn}>ඉල්ලීම යොමු කරන්න</button>
                    </form>
                </div>
            )}

            <div style={styles.searchBar}>
                <Lucide.Search size={18} color="#999" />
                <input type="text" placeholder="සොයන්න (නම හෝ NIC)..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} style={styles.searchInput} />
            </div>

            <div style={styles.listSection}>
                <div style={styles.grid}>
                    {filteredAppointments.length > 0 ? filteredAppointments.map(app => (
                        <div key={app._id} style={styles.appCard}>
                            <div style={styles.cardInfo}>
                                <strong>{app.userName || app.name || app.username || "User"} <small style={{color: '#777'}}>({app.nic})</small></strong>
                                <p style={styles.pTag}><Lucide.Info size={14} /> {app.reason}</p>
                                <p style={styles.pTag}><Lucide.Clock size={14} /> {app.date} | {app.time}</p>
                            </div>
                            <div style={styles.statusSection}>
                                <span style={{...styles.badge, backgroundColor: app.status === 'Approved' ? '#22c55e' : app.status === 'Rejected' ? '#ef4444' : '#f59e0b'}}>{app.status}</span>
                                <div style={styles.actions}>
                                    {isOfficer && app.status === 'Pending' && (
                                        <>
                                            <button onClick={() => updateStatus(app._id, 'Approved')} style={styles.approveBtn} title="Approve"><Lucide.Check size={16}/></button>
                                            <button onClick={() => updateStatus(app._id, 'Rejected')} style={styles.rejectBtn} title="Reject"><Lucide.X size={16}/></button>
                                        </>
                                    )}
                                    {(isOfficer || app.status === 'Pending') && (
                                        <button onClick={() => deleteAppointment(app._id)} style={styles.deleteBtn} title="Delete"><Lucide.Trash2 size={16} /></button>
                                    )}
                                </div>
                            </div>
                        </div>
                    )) : <p style={{textAlign: 'center', color: '#999', padding: '20px'}}>කිසිදු පත්වීමක් හමු නොවීය.</p>}
                </div>
            </div>
        </div>
    );
}

const styles = {
    container: { padding: '30px 20px', maxWidth: '900px', margin: 'auto', fontFamily: 'sans-serif', backgroundColor: '#f8fafc' },
    headerRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' },
    mainTitle: { display: 'flex', alignItems: 'center', gap: '10px', color: '#800000', margin: 0 },
    pdfBtn: { display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 15px', backgroundColor: '#1e293b', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' },
    statsRow: { display: 'flex', gap: '15px', marginBottom: '20px' },
    statCard: { flex: 1, background: '#fff', padding: '15px', borderRadius: '10px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)', textAlign: 'center' },
    statLabel: { fontSize: '11px', color: '#777', fontWeight: 'bold', textTransform: 'uppercase' },
    statValue: { fontSize: '22px', margin: '5px 0 0 0', color: '#334155' },
    chartSection: { background: '#fff', padding: '20px', borderRadius: '12px', boxShadow: '0 2px 10px rgba(0,0,0,0.05)', marginBottom: '25px' },
    formSection: { background: '#fff', padding: '20px', borderRadius: '12px', boxShadow: '0 4px 15px rgba(0,0,0,0.1)', marginBottom: '30px' },
    form: { display: 'flex', flexDirection: 'column', gap: '10px' },
    row: { display: 'flex', gap: '10px' },
    input: { padding: '10px', borderRadius: '6px', border: '1px solid #ddd' },
    searchBar: { display: 'flex', alignItems: 'center', gap: '10px', background: '#fff', padding: '10px', borderRadius: '8px', border: '1px solid #ddd', marginBottom: '20px' },
    searchInput: { border: 'none', outline: 'none', width: '100%' },
    bookBtn: { padding: '12px', backgroundColor: '#800000', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' },
    errorMsg: { color: '#ef4444', fontSize: '14px' },
    appCard: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px', background: '#fff', border: '1px solid #eee', borderRadius: '10px', marginBottom: '10px', transition: '0.3s' },
    cardInfo: { display: 'flex', flexDirection: 'column', gap: '5px' },
    pTag: { display: 'flex', alignItems: 'center', gap: '5px', margin: 0, fontSize: '13px', color: '#555' },
    statusSection: { textAlign: 'right', display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '10px' },
    badge: { padding: '4px 10px', borderRadius: '15px', color: 'white', fontSize: '10px', fontWeight: 'bold' },
    actions: { display: 'flex', gap: '8px' },
    approveBtn: { background: '#22c55e', color: 'white', border: 'none', padding: '6px', borderRadius: '4px', cursor: 'pointer' },
    rejectBtn: { background: '#ef4444', color: 'white', border: 'none', padding: '6px', borderRadius: '4px', cursor: 'pointer' },
    deleteBtn: { background: '#fef2f2', color: '#ef4444', border: '1px solid #fee2e2', padding: '6px', borderRadius: '4px', cursor: 'pointer' }
};

export default AppointmentPage;